version: '3.4'

services:
  dwapi:
    image: kenyahmis/dwapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5757:5757"
    - "5753:5753"
    restart: unless-stopped
