name: Check PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.805
      - name: Install dependencies
        run: dotnet restore Dwapi.sln
      - name: Build
        run: dotnet build src/Dwapi/Dwapi.csproj --configuration Release --no-restore
      - name: Test
        run: ls test/*/*Tests.csproj | xargs -L 1 dotnet test
